<a href="https://colab.research.google.com/github/Aleksandra0001/DataScience/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

1.Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет изначально?


In [ ]:
A = np.matrix("1, 1, 1; 0.05, 0.07, 0; 0.05, 0, 0.06")
b = np.array([50000, 2250, 1400])
x = np.linalg.solve(A, b)
x

array([10000., 25000., 15000.])

2.На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?

x1+x2+x3=1328
-x1+x2+0=120
x1+0-x3=100

In [ ]:
A = np.matrix("1, 1, 1; -1, 1, 0; 1, 0, -1")
b = np.array([1358, 120, 100])
x = np.linalg.solve(A, b)
x

array([446., 566., 346.])

3.Составьте каноническое уравнение эллипсоида, проходящего через три точки A, B и C: A(sqrt{3}; 0; sqrt{3}) B(sqrt(6); 0.5; 0) C(1; sqrt(3)^-1; 1)
Каноническое уравнение эллипсоида в прямоугольной декартовой системе координат имеет вид: x^2/a^2 + y^2/b^2 + z^2/c^2 = 1 Задача состоит в определении параметров a^2, b^2 и c^2

*   d = 1/a^2
*   e=1/b^2
*   f=1/c^2

In [ ]:
A=np.array([[3, 0, 3],[6,0.25,0],[1,1/3, 1]])
v=np.array([1,1,1])
l=np.linalg.solve(A, v)
result=1/l
result

array([12. ,  0.5,  4. ])

4.Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2). Необходимо найти коэффициенты уравнения a,b,ca,b,c

y=a⋅x^2+b⋅x+c

a+b+c=12

9a+3b+c=54

a-b+c=2


In [ ]:
B=np.matrix("1,1,1;9,3,1;1,-1,1")
g=np.array([12,54,2])
res=np.linalg.solve(B, g)
res

array([4., 5., 3.])

**5.Составьте функцию get_polynom, которая по набору точек вида (x1,y1),(x2,y2)**

, ..., (x{n+1}, y{n+1})(x1 ,y1),(x2,y 2),…,(xn+1,yn+1) будет находить коэффициенты [многочлена](https://ru.wikipedia.org/wiki/%D0%9C%D0%BD%D0%BE%D0%B3%D0%BE%D1%87%D0%BB%D0%B5%D0%BD) ci. Таким образом функция принимает список кортежей с координатами и возвращает набор коэффициентов c0,ci,... cn c0,ci,…,cn
​

---




In [ ]:
def get_polynom(coords):
    # for i in reversed(range(len(coords))):
    #   print(i)
    A=np.matrix([[coord[0]**i for i in reversed(range(len(coords)))] for coord in coords])
    v=np.array([coord[1] for coord in coords]) 
  
    return np.linalg.solve(A, v)


In [ ]:

get_polynom([(1,12), (3,54), (-1,2)])

array([4., 5., 3.])